title = "viazure"
baseURL = 'https://viazure.cc/'

# This is what goes in <html lang="">
languageCode = 'zh'

# This defines how dates are formatted
defaultContentLanguage = "zh"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

# traditional way: theme component resides in directory 'themes'
theme = "hugo-blog-awesome"

# modern way: pull in theme component as hugo module
#[module]
  # Uncomment the next line to build and serve using local theme clone declared in the named Hugo workspace:
  # workspace = "hugo-blog-awesome.work"
  #[module.hugoVersion]
    #extended = true
    #min = "0.87.0"
  #[[module.imports]]
    #path = "github.com/hugo-sid/hugo-blog-awesome"
    #disable = false

[services]
# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable Google Analytics, simply leave the field empty or remove the next two lines
  [services.googleAnalytics]
    id = '' # G-MEASUREMENT_ID

# To enable Disqus comments, provide Disqus Shortname below.
# To disable Disqus comments, simply leave the field empty or remove the next two lines
  [services.disqus]
    shortname = ''

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2 # ToC starts from H2
    endLevel = 4 # ToC ends at H4
    ordered = false # generates <ul> instead of <ol>

############################## Chinese language ################################
[Languages.zh]
  languageName = "Chinese"
  languageCode = "zh"
  contentDir = "content/zh"
  weight = 1

  [Languages.zh.menu]
  [[Languages.zh.menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = '首页'
    url = '/'
    weight = 10
  [[Languages.zh.menu.main]]
    pageRef="posts"
    name = '文章'
    url = '/posts/'
    weight = 20
  [[Languages.zh.menu.main]]
    pageRef="about"
    name = '关于'
    url = '/about/'
    weight = 30

[Languages.zh.params]
  sitename = "viazure"
  defaultColor = "auto" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
  # the default value is set to 'auto'.
  # You can take a look at layouts/index.html for more information.
  description = "Look forward, don't look back."
  mainSections = ['posts']
  toc = false # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
  # Your custom scripts will be concatenated to one file `custom.js`.
  # When building for production it will be minified.
  # The file `custom.js` is loaded on each page (before body tag ends).
  dateFormat = "2006-01-02" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
  # See https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for available date formats.
  rssFeedDescription = "full" # available options: 1) summary 2) full
  # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
  # full - includes full blog post in the RSS feed. Generated using Hugo .Content .
  # By default (or if nothing is specified), summary is used.

[Languages.zh.params.author]
  avatar = "avatar.png" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "viazure"
  name = "viazure"
  description = "向前看，别回头。"

# Allow to override webmanifest options
[Languages.zh.params.webmanifest]
  name = "sitename" # will use "params.sitename" or "title" by default
  short_name = "sitename" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"


# Allow to override `browserconfig.xml` params (configuration for windows embedded browsers)
[params.browserconfig]
  TileColor = "#2d89ef" # default windows 10 blue tile color


[[params.socialIcons]]
name = "github"
url = "https://github.com/viazure"

[[params.socialIcons]]
name = "running"
url = "https://run.viazure.cc"


[[params.socialIcons]]
name = "Rss"
url = "/index.xml"
